#!/bin/bash
ROUTE=${ROUTE:-localhost:8082}
curl -X POST ${ROUTE}/recommendations/idugalic/likes/1 -H "Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0MjE5MDI4ODIsInVzZXJfbmFtZSI6ImlkdWdhbGljIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiIyNGIxY2JlMS00MzU1LTQ2NzQtODFjZC02YWUyYmQyZTA5NTIiLCJjbGllbnRfaWQiOiJhY21lIiwic2NvcGUiOlsib3BlbmlkIiwicmVhZF9jYXRhbG9nIiwid3JpdGVfY2F0YWxvZyIsInJlYWRfb3JkZXJzIiwid3JpdGVfb3JkZXJzIiwicmVhZF9yZXZpZXdzIiwid3JpdGVfcmV2aWV3cyIsInJlYWRfcmVjb21tZW5kYXRpb25zIiwid3JpdGVfcmVjb21tZW5kYXRpb25zIl19.Z68bsvOZLfMzoqOh_jbu_O9DddKOdIoCDhFEjEiqXCX9uNC5hDXvcUhNpH1haz6vim10LQyDYaZopUYtU1JRwpXsmOMcYyNGZv-xnIbAL84V4qUn8zCvkTUL2qU1tAteDS-lLSLIts6Jm6DomirkuULx_ne5cOH1pdSXxtqyLvOJSDzfk91a4d3fNFjf9Hob7biXxqBR9SHu8BS3CkUL0uM9O2d0t4_x87n9TG9IVyAuwiTnVLGo0kKq1IAlzul9NMSjXnpJGZo39RVIjG0b9PQtOSUILtj6ZkewcHI_PooKmaUfaTcx4O2IiWVnpcmRZlIdLWGJvySLLRdDwxmbJA"
curl -X POST ${ROUTE}/recommendations/idugalic/likes/2
curl -X POST ${ROUTE}/recommendations/idugalic/likes/2
curl -X POST ${ROUTE}/recommendations/odugalic/likes/4
curl -X POST ${ROUTE}/recommendations/odugalic/likes/5
curl -X POST ${ROUTE}/recommendations/odugalic/likes/2
curl -X POST ${ROUTE}/recommendations/hdugalic/likes/3
curl -X POST ${ROUTE}/recommendations/hdugalic/likes/5
